# Generated by Django 2.1.5 on 2019-01-30 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190129_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 1, 14, 17, 54, 797362, tzinfo=utc)),
        ),
    ]
