# Generated by Django 2.1.5 on 2019-01-30 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190130_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 14, 25, 57, 532064, tzinfo=utc), null=True),
        ),
    ]
