# Generated by Django 2.1.5 on 2019-01-30 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20190130_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 15, 38, 22, 671575, tzinfo=utc), null=True),
        ),
    ]
