# Generated by Django 2.1.5 on 2019-02-05 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_auto_20190206_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 21, 38, 32, 950069, tzinfo=utc), null=True),
        ),
    ]
