# Generated by Django 2.1.5 on 2019-02-06 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_auto_20190206_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 9, 23, 29, 95460, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='language',
            field=models.CharField(blank=True, max_length=128, verbose_name='язык'),
        ),
    ]
