# Generated by Django 2.1.5 on 2019-02-06 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_auto_20190206_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 11, 17, 58, 611900, tzinfo=utc), null=True),
        ),
    ]
