# Generated by Django 2.1.5 on 2019-01-30 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190130_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 1, 14, 18, 2, 726176, tzinfo=utc)),
        ),
    ]
