# Generated by Django 2.1.7 on 2019-02-26 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0045_auto_20190220_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 21, 29, 43, 660314, tzinfo=utc), null=True),
        ),
    ]
